
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"

[[inputs.mqtt_consumer]]
  servers = ["tls://40bbfbeb8fd548a5b4c9d54d2057bda6.s1.eu.hivemq.cloud:8883"]
  topics = [
    "equipment/+/telemetry"
  ]
  
  # Persistent Session Configuration
  qos = 1
  client_id = "vistasystems_demo_server"
  persistent_session = true

  username = "kasun"
  password = "kasua1U23"
  data_format = "json"
  
  # Timestamp Parsing Configuration
  json_time_key = "timestamp"
  json_time_format = "unix"
  
  name_override = "telemetry"
  
  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "equipment/+/telemetry"
    tags = "_/device_id/_"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "QLn2VxYdkLyOS8aHtoAC1D3lC5adHKQM4H0ko0xAWNNSMssGDvtQQO6dlD4_TvceOdEVkWNiw5BbnLBpNwkxnQ=="
  organization = "vistasystems"
  bucket = "telemetry"